pipeline {
    agent {
        label 'docker' // Replace with your agent label
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds') // Replace with your DockerHub credentials ID
    }
    parameters {
        string(name: 'VERSION', defaultValue: 'latest', description: 'Version number for tagging the Docker image')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build("alymkulovabk/simplepage:${params.VERSION}", "-f ./Day2/Dockerfile .")
                }
            }
        }
        stage('Login to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        def dockerImage = docker.image("alymkulovabk/simplepage:${params.VERSION}")
                        dockerImage.push()
                    }
                }
            }
        }
    }
    post {
        failure {
            echo 'The build failed.'
        }
        success {
            echo 'The build and push were successful.'
        }
    }
}


